<a href="https://colab.research.google.com/github/trijot/PricingWorkshop_RPM2026/blob/main/github101" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

!git clone https://github.com/trijot/PricingWorkshop_RPM2026.git

Cloning into 'PricingWorkshop_RPM2026'...
remote: Enumerating objects: 204, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 204 (delta 9), reused 1 (delta 1), pack-reused 185 (from 2)
Receiving objects: 100% (204/204), 431.69 MiB | 28.90 MiB/s, done.
Resolving deltas: 100% (97/97), done.

In [2]:
%cd PricingWorkshop_RPM2026

/content/PricingWorkshop_RPM2026

In [3]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [4]:
ls

'Personal Auto Policy Data and Rate Tables'/      rater_files/
'Personal Auto Policy Data and Rate Tables.zip'  'RPM 2026.pptx'
 PriorRateTables_RatingAlgorithm.xlsx            'Welcome to Github'

In [5]:
!find . -type f

./.git/index
./.git/HEAD
./.git/logs/HEAD
./.git/logs/refs/remotes/origin/HEAD
./.git/logs/refs/heads/main
./.git/info/exclude
./.git/objects/pack/pack-d638eb1eec6e30ddf26f5350e197a689397b4bb0.idx
./.git/objects/pack/pack-d638eb1eec6e30ddf26f5350e197a689397b4bb0.pack
./.git/config
./.git/refs/remotes/origin/HEAD
./.git/refs/heads/main
./.git/description
./.git/hooks/pre-push.sample
./.git/hooks/commit-msg.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/update.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-commit.sample
./.git/packed-refs
./PriorRateTables_RatingAlgorithm.xlsx
./RPM 2026.pptx
./Personal Auto Policy Data and Rate Tables.zip
./rater_files/rate_tables.xlsx
./rater_files/dashboard.html
./rater_files/.ipynb_checkpoints/olp-checkpoint.py
./rater_files/.ipynb_checkpoints/Untitled-checkpoint.ipynb
./rater_files/.ipynb_checkpoints/olep-checkpoint.py
./rater_files/.ipynb_checkpoints/olp-checkpoint.ipynb
./rater_files/.ipynb_checkpoints/dashboard-checkpoint.py
./rater_files/rated_policies.zip
./rater_files/olp.py
./rater_files/dashboard.py
./rater_files/olep.py
./rater_files/Untitled.ipynb
./rater_files/olep.zip
./rater_files/Personal Auto Dataset and Premiums.csv
./rater_files/olp.ipynb
./Personal Auto Policy Data and Rate Tables/RateTables_RatingAlgorithm.xlsx
./Personal Auto Policy Data and Rate Tables/Personal Auto Dataset and Premiums.csv
./Welcome to Github

In [6]:
!git branch

* main

In [7]:
!git pull origin main

From https://github.com/trijot/PricingWorkshop_RPM2026
 * branch            main       -> FETCH_HEAD
Already up to date.

In [8]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [9]:
%cd PricingWorkshop_RPM2026
!git status

[Errno 2] No such file or directory: 'PricingWorkshop_RPM2026'
/content/PricingWorkshop_RPM2026
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [10]:
!cd /content/PricingWorkshop_RPM2026 && git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [11]:
!cd /content/PricingWorkshop_RPM2026 && git config user.name "Trijot Singh"
!cd /content/PricingWorkshop_RPM2026 && git config user.email "trijotsingh@gmail.com"

In [12]:
!find /content/PricingWorkshop_RPM2026 -maxdepth 2 -type d

/content/PricingWorkshop_RPM2026
/content/PricingWorkshop_RPM2026/.git
/content/PricingWorkshop_RPM2026/.git/branches
/content/PricingWorkshop_RPM2026/.git/logs
/content/PricingWorkshop_RPM2026/.git/info
/content/PricingWorkshop_RPM2026/.git/objects
/content/PricingWorkshop_RPM2026/.git/refs
/content/PricingWorkshop_RPM2026/.git/hooks
/content/PricingWorkshop_RPM2026/rater_files
/content/PricingWorkshop_RPM2026/rater_files/.ipynb_checkpoints
/content/PricingWorkshop_RPM2026/Personal Auto Policy Data and Rate Tables

In [13]:
import pandas as pd
import numpy as np
import random

# Number of policyholders
n = 100

# Sample values
cities = ["Toronto", "Vancouver", "Calgary", "Winnipeg", "Montreal", "Ottawa"]
genders = ["Male", "Female"]
policy_types = ["Auto", "Home", "Travel", "Health"]
vehicle_types = ["Sedan", "SUV", "Truck", "Electric", "Hybrid"]

data = {
    "Policy_ID": [f"P{1000+i}" for i in range(n)],
    "Member_ID": [f"M{5000+i}" for i in range(n)],
    "Age": np.random.randint(18, 75, n),
    "Gender": [random.choice(genders) for _ in range(n)],
    "City": [random.choice(cities) for _ in range(n)],
    "Policy_Type": [random.choice(policy_types) for _ in range(n)],
    "Vehicle_Type": [random.choice(vehicle_types) for _ in range(n)],
    "Annual_Premium": np.round(np.random.uniform(300, 2000, n), 2),
    "Claim_Count": np.random.poisson(0.3, n),
    "Policy_Start_Year": np.random.randint(2018, 2025, n)
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("sample_policyholders.csv", index=False)

# Preview
df.head()

,Policy_ID,Member_ID,Age,Gender,City,Policy_Type,Vehicle_Type,Annual_Premium,Claim_Count,Policy_Start_Year
0,P1000,M5000,35,Female,Calgary,Home,SUV,300.65,0,2018
1,P1001,M5001,18,Male,Montreal,Health,Truck,1483.09,1,2020
2,P1002,M5002,33,Female,Toronto,Home,SUV,1308.21,2,2024
3,P1003,M5003,26,Male,Winnipeg,Home,Sedan,506.70,2,2018
4,P1004,M5004,53,Female,Toronto,Home,Hybrid,1718.03,0,2021

In [14]:
!git config user.name "Trijot Singh"
!git config user.email "trijotsingh@gmail.com"

In [15]:
!git add .
!git commit -m "Resolve merge conflict and merge feature-update-rates"

[main 944b711] Resolve merge conflict and merge feature-update-rates
 1 file changed, 101 insertions(+)
 create mode 100644 sample_policyholders.csv

In [16]:
!git status

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [23]:
!git config user.name "Trijot Singh"
!git config user.email "trijotsingh@gmail.com"
!git branch
!git status

* main
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [24]:
from getpass import getpass
token = getpass("GitHub token: ")

GitHub token: ··········

In [27]:
!git push https://trijot:{token}@github.com/trijot/PricingWorkshop_RPM2026.git main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.96 KiB | 1.96 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/trijot/PricingWorkshop_RPM2026.git
   6a2346e..944b711  main -> main

In [28]:
!git log --oneline --graph --decorate --all

* 944b711 (HEAD -> main) Resolve merge conflict and merge feature-update-rates
* 6a2346e (origin/main, origin/HEAD) Github Basics
* 8f6eb2a Delete .gitignore
* 9b417af Delete LICENSE
* 3dd99b1 Delete README.md
* 60b7538 Delete Image_20260205_135649_393.jpeg
* e34df19 Delete Github intro.pptx
* 493adcc Delete Github intro.key
* 2ac69c6 Delete scripts_tools directory
* 3a794de Update RPM 2026.pptx
*   ad06c7c Merge branch 'main' of https://github.com/trijot/PricingWorkshop_RPM2026
|\
| * 97aefe0 Colab test
| * 918b16f Colab test
| * bb70d00 Deleted files
* | 938af61 Update RPM 2026.pptx
|/
* 36b5592 Update RPM 2026.pptx
*   f4755ca Merge branch 'main' of https://github.com/trijot/PricingWorkshop_RPM2026
|\
| * 8644176 Zipped indication upload
* | 920cf75 Update RPM 2026.pptx
|/
* 6a71422 Update RPM 2026.pptx
* 6c09434 Indication update
* 99d4514 Slide update Malloy
* 3862fcc Updates from working session
* bfeef7d RPM 2026
* 88637d8 Updated ppt for submission
* fdefabd trijotsingh_Picture
*   a9e732e Merge branch 'main' of https://github.com/trijot/PricingWorkshop_RPM2026 into main
|\
| * 1eb3b27 RPM Slide - Update Nitai
* | 51eeca8 Wasim Update 2.26
|/
* d37db11 Updated_nitai
* 077fa37 Indication update
* c8d622f indication update
* e03e398 GitHub intro
* 7dbed9c Slide Update
* 5064a4c Delete RPM 2026_20250205.pptx
* dfdd9c9 Add files via upload
* 6f40a07 Branch update
* 47d7f06 dashboard_path_updated
* a68a07a Create dashboard
* 1fcca39 Create olp
* 12cc9f6 Initial rater/excel slides
* 982f13e Add files via upload
* e97781a Script update
* 36c343a Simulated_losses
* 0d72109 Update README.md
* 9d4733a Delete RateTables_RatingAlgorithm.xlsx
* d6ce251 Add files via upload
* a0feb79 Add files via upload
* ab2db7d Update README.md
* 6cc939f Update README.md
* d2daa72 Update README.md
* b1ad964 Update README.md
* a82bd7b Initial commit

In [29]:
%cd /content/PricingWorkshop_RPM2026
!git config user.name "Trijot Singh"
!git config user.email "trijotsingh@gmail.com"
!git checkout -b feature-add-policy-csv || git checkout feature-add-policy-csv

import pandas as pd
import numpy as np

n = 100
df = pd.DataFrame({
    "policy_id": [f"P{1000+i}" for i in range(n)],
    "member_id": [f"M{5000+i}" for i in range(n)],
    "age": np.random.randint(18, 75, n),
    "gender": np.random.choice(["Male", "Female"], n),
    "province": np.random.choice(["MB", "ON", "BC", "AB"], n),
    "policy_type": np.random.choice(["Auto", "Home", "Travel"], n),
    "annual_premium": np.round(np.random.uniform(300, 2500, n), 2),
    "claim_count": np.random.poisson(0.3, n)
})
df.to_csv("sample_policyholders_100.csv", index=False)

!git add sample_policyholders_100.csv
!git commit -m "Add sample policyholder CSV with 100 members"

/content/PricingWorkshop_RPM2026
Switched to a new branch 'feature-add-policy-csv'
[feature-add-policy-csv f128a98] Add sample policyholder CSV with 100 members
 1 file changed, 101 insertions(+)
 create mode 100644 sample_policyholders_100.csv

In [31]:
from getpass import getpass
token = getpass("Paste GitHub token: ")
!git push https://trijot:{token}@github.com/trijot/PricingWorkshop_RPM2026.git feature-add-policy-csv

Paste GitHub token: ··········
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.58 KiB | 1.58 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote:
remote: Create a pull request for 'feature-add-policy-csv' on GitHub by visiting:
remote:      https://github.com/trijot/PricingWorkshop_RPM2026/pull/new/feature-add-policy-csv
remote:
To https://github.com/trijot/PricingWorkshop_RPM2026.git
 * [new branch]      feature-add-policy-csv -> feature-add-policy-csv

In [32]:
%cd /content/PricingWorkshop_RPM2026
!pwd
!git status

/content/PricingWorkshop_RPM2026
/content/PricingWorkshop_RPM2026
On branch feature-add-policy-csv
nothing to commit, working tree clean

In [33]:
!git config user.name "Trijot Singh"
!git config user.email "trijotsingh@gmail.com"

In [34]:
!git checkout -b feature-add-policy-csv

fatal: A branch named 'feature-add-policy-csv' already exists.

In [35]:
!git checkout feature-add-policy-csv

Already on 'feature-add-policy-csv'

In [37]:
import pandas as pd
import numpy as np

n = 100

df = pd.DataFrame({
    "policy_id": [f"P{1000+i}" for i in range(n)],
    "member_id": [f"M{5000+i}" for i in range(n)],
    "age": np.random.randint(18, 70, n),
    "gender": np.random.choice(["Male", "Female"], n),
    "province": np.random.choice(["MB", "ON", "BC", "AB"], n),
    "policy_type": np.random.choice(["Auto", "Home", "Travel"], n),
    "annual_premium": np.round(np.random.uniform(300, 2500, n), 2),
    "claim_count": np.random.poisson(0.3, n)
})

csv_path = "/content/PricingWorkshop_RPM2026/sample_policyholders_100.csv"
df.to_csv(csv_path, index=False)

df.head()

,policy_id,member_id,age,gender,province,policy_type,annual_premium,claim_count
0,P1000,M5000,27,Male,ON,Home,2264.49,0
1,P1001,M5001,53,Female,ON,Travel,381.96,0
2,P1002,M5002,51,Male,BC,Travel,1177.19,0
3,P1003,M5003,57,Female,BC,Travel,560.35,0
4,P1004,M5004,46,Female,BC,Home,1595.43,0

In [38]:
!ls -l /content/PricingWorkshop_RPM2026
!git status

total 30576
drwxr-xr-x 2 root root     4096 Mar 13 02:58 'Personal Auto Policy Data and Rate Tables'
-rw-r--r-- 1 root root  5554971 Mar 13 02:58 'Personal Auto Policy Data and Rate Tables.zip'
-rw-r--r-- 1 root root    20185 Mar 13 02:58  PriorRateTables_RatingAlgorithm.xlsx
drwxr-xr-x 3 root root     4096 Mar 13 02:58  rater_files
-rw-r--r-- 1 root root 25698703 Mar 13 02:58 'RPM 2026.pptx'
-rw-r--r-- 1 root root     4004 Mar 13 03:37  sample_policyholders_100.csv
-rw-r--r-- 1 root root     5704 Mar 13 03:01  sample_policyholders.csv
-rw-r--r-- 1 root root     7640 Mar 13 02:58 'Welcome to Github'
On branch feature-add-policy-csv
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   sample_policyholders_100.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [39]:
!git add sample_policyholders_100.csv
!git commit -m "Add sample policyholder CSV with 100 members"

[feature-add-policy-csv 066d4dd] Add sample policyholder CSV with 100 members
 1 file changed, 101 insertions(+), 101 deletions(-)
 rewrite sample_policyholders_100.csv (97%)

In [40]:
from getpass import getpass
token = getpass("Paste GitHub token: ")
!git push https://trijot:{token}@github.com/trijot/PricingWorkshop_RPM2026.git feature-add-policy-csv

Paste GitHub token: ··········
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.57 KiB | 1.57 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/trijot/PricingWorkshop_RPM2026.git
   f128a98..066d4dd  feature-add-policy-csv -> feature-add-policy-csv